# https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# See supported Node.js release schedule at https://nodejs.org/en/about/releases/
env:
  NODE_VERSION: 22.x

jobs:
  test_jest:
    name: Test with jest-axe

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    # Demo - ignore non-zero exit codes for "test".
    - name: Audit URLs using jest-axe
      run: npm test || true

  test_lighthouseci:
    name: Test with Lighthouse-CI

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    # https://github.com/treosh/lighthouse-ci-action
    - name: Audit URLs using Lighthouse
      uses: treosh/lighthouse-ci-action@v12
      with:
        configPath: './lighthouserc.js'
        # urls: |
        #  https://example.com/
        #  https://example.com/blog
        # budgetPath: ./budget.json # test performance budgets
        uploadArtifacts: true # save results as an action artifact
        temporaryPublicStorage: true # upload lighthouse report to the temporary storage

# End.
